columnSuffix: jmcdadcv
contentColumnType: text
fieldGroup: a0b38ead-1425-4026-a02e-ba4ce78d998c # Form
handle: fieldFirstname
instructions: ''
name: Firstname
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
