columnSuffix: null
contentColumnType: string
fieldGroup: 50a94eac-3741-4dc1-8227-7add9f01a6c1 # Common
handle: fieldContent
instructions: ''
name: Content
searchable: false
settings:
  contentTable: '{{%matrixcontent_fieldcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
